-- Script was generated by Devart dbForge Studio Express for MySQL, Version 6.0.568.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 29/11/2013 13:04:13
-- Server version: 5.5.31-0+wheezy1
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE fet10009689;

--
-- Definition for table CrimeStatistics
--
DROP TABLE IF EXISTS CrimeStatistics;
CREATE TABLE CrimeStatistics (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Homicide INT(11) DEFAULT NULL,
  ViolenceWithInjury INT(11) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table GeographicReference
--
DROP TABLE IF EXISTS GeographicReference;
CREATE TABLE GeographicReference (
  Id INT(11) NOT NULL,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table Area
--
DROP TABLE IF EXISTS Area;
CREATE TABLE Area (
  GeographicReference_id INT(11) NOT NULL AUTO_INCREMENT,
  CrimeStatistics_Id INT(11) DEFAULT NULL,
  PRIMARY KEY (GeographicReference_id),
  CONSTRAINT FK_Area_CrimeStatistics_Id FOREIGN KEY (CrimeStatistics_Id)
    REFERENCES CrimeStatistics(Id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Area_GeographicReference_Id FOREIGN KEY (GeographicReference_id)
    REFERENCES GeographicReference(Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table Country
--
DROP TABLE IF EXISTS Country;
CREATE TABLE Country (
  GeographicReference_Id INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (GeographicReference_Id),
  UNIQUE INDEX UK_Country_GeographicReference (GeographicReference_Id),
  CONSTRAINT FK_Country_GeographicReference_Id FOREIGN KEY (GeographicReference_Id)
    REFERENCES GeographicReference(Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table National
--
DROP TABLE IF EXISTS National;
CREATE TABLE National (
  GeographicReference_Id INT(11) NOT NULL AUTO_INCREMENT,
  CrimeStatistics_Id INT(11) DEFAULT NULL,
  PRIMARY KEY (GeographicReference_Id),
  CONSTRAINT FK_National_CrimeStatistics_Id FOREIGN KEY (CrimeStatistics_Id)
    REFERENCES CrimeStatistics(Id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_National_GeographicReference_Id FOREIGN KEY (GeographicReference_Id)
    REFERENCES GeographicReference(Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table Region
--
DROP TABLE IF EXISTS Region;
CREATE TABLE Region (
  GeographicReference_Id INT(11) NOT NULL DEFAULT 0,
  Country_Id INT(11) DEFAULT NULL,
  PRIMARY KEY (GeographicReference_Id),
  CONSTRAINT FK_Region_Country_GeographicReference_Id FOREIGN KEY (Country_Id)
    REFERENCES Country(GeographicReference_Id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_Region_GeographicReference_Id FOREIGN KEY (GeographicReference_Id)
    REFERENCES GeographicReference(Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;